# Generated by Django 3.2.11 on 2022-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_hotelimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
