# Generated by Django 3.2.11 on 2022-03-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0008_hotels_hotel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('promocode', models.CharField(default='', max_length=255)),
                ('brand_name', models.CharField(default='', max_length=255)),
                ('terms_condition', models.CharField(default='', max_length=255)),
                ('logo', models.ImageField(upload_to='brand_logo')),
            ],
        ),
    ]
